### PR TITLE
Added Custom Element

### PR DESCRIPTION
**Pull request by Joltrix**
Needed for the custom element addition in the People application

### CODE REVIEW

**Comment by Joltrix** [comment]
This is needed for [StarcounterSamples/People#33](https://github.com/StarcounterSamples/People/issues/33)

**Comment by warpech** [comment]
The name "CustomElement" sounds like related to [Custom Elements](https://w3c.github.io/webcomponents/spec/custom/) which is a subset of W3C Web Components spec - a thing that we actually use in our apps, so it might get confusing.

Could this please be renamed to `CustomContactInfo`, `CustomContactInfoRelation`, `CustomContactInfoRelationType`?

**Comment by miyconst** [comment]
I agree with what @warpech says.

**Comment by Joltrix** [comment]
Okay, I'll fix this first thing tomorrow!

**Comment by warpech** [comment]
Looks good, merging

**Comment by warpech** [comment]
Should be available in Starcounter starting from tonight's nightly build

**Pull request merged**
