### PR TITLE
Adapt Simplified to breaking changes in 2.4 / Develop

### PR DESCRIPTION
**Pull request by per-samuelsson**
What the title says. Basically, I'm changing how Starcounter relate to "special assemblies" in Starcounter 2.4. Maybe the most surfacing change for developers is that now, references from projects are standardized - you reference what you use (no magic) and references are Copy Local (as would be the least surprise).

### CODE REVIEW

**Comment by per-samuelsson** [comment]
The umbrella for the big hosting redesign in 2.4 that is about to happen (forcing this proposed PR) is https://github.com/Starcounter/Starcounter/issues/3869. Once I merge that into Develop, I'll reconfigure TC to bring in Simplified Develop rather than Master.

**Comment by per-samuelsson** [comment]
Some discussion in corresponding issue: #36.

**Comment by per-samuelsson** [comment]
@warpech Bump

**Comment by warpech** [comment]
Simplified does not build with Starcounter 2.3 after these changes, so it is preferable to merge this branch only when we are sure that it works with Starcounter 2.4 - so there is at least one Starcounter that it works with.

Starting from this merge, we cannot make a simple merge in Simplified from `develop` to `master`. Will need to use cherry picking.

But this is fine. 

I will continue testing later today.

**Comment by per-samuelsson** [comment]
@warpech 

Thanks for reviewing. I had to merge this to be able to move forward with all upcoming 2.4 features. If it mess something up for you guys, just let me know and I'll help! 

I have now adapted our build system to your branching policies: https://github.com/Starcounter/Announcements/issues/13

**Pull request merged**
